name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: setup-java
        name: setup-java
        uses: actions/setup-java@v3
        with:
          cache: maven
          distribution: corretto
          java-version: 17
      - id: maven-verify
        name: maven-verify
        run: mvn verify --batch-mode
